version: "3.8"

services:
  web:
    build: .
    container_name: drupal_web
    ports:
      - "8089:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
